### ISSUE TITLE
Problems pip installing the package

### ISSUE THREAD

**Issue by Excaliburg** [peytondmurray/PyFORC#8]
Hey! 

I tried installing the package following your gide and it seems to be missing a line in the "setup.py" file. You should add this line: **py_modules=[]**, inside the setup() in order to avoid getting this error:

"error: Multiple top-level packages discovered in a flat-layout: ['assets', 'pyforc', 'notebooks'].

To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.

If you are trying to create a single distribution with multiple packages
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:

1. set up custom discovery (`find` directive with `include` or `exclude`)
2. use a `src-layout`
3. explicitly set `py_modules` or `packages` with a list of names

To find more information, look for "package discovery" on setuptools docs."

**Comment by peytondmurray** [comment]
Hey, sorry I missed this somehow back in October. I wrote this a long while back - let me see how I can reorganize this into a sensible layout. Hang on...

**Comment by peytondmurray** [comment]
@Excaliburg I did a bunch of maintenance fixes today, tested in a fresh environment, and it all seems to be running just fine again. Can you please try installing again and let me know if you hit any trouble?

Sorry again about the slow response here!

**Comment by Excaliburg** [comment]
Thanks! I had no problem in installing it now. :)
